<?php

return [
    /*
     * Concrete model identifiers are environment/configuration, never domain constants.
     * An alias with no configured model remains unavailable and routing fails closed or
     * uses the configured fallback when that fallback satisfies every role requirement.
     */
    'models' => [
        'openai_frontier' => [
            'provider' => 'openai',
            'model' => env('OPENAI_FRONTIER_MODEL'),
            'capabilities' => ['reasoning', 'coding', 'large_context', 'structured_output', 'tool_calling', 'security_analysis'],
            'tools' => ['repository_read', 'pull_request_read', 'web_search'],
        ],
        'anthropic_frontier' => [
            'provider' => 'anthropic',
            'model' => env('ANTHROPIC_FRONTIER_MODEL'),
            'capabilities' => ['reasoning', 'coding', 'large_context', 'structured_output', 'tool_calling', 'security_analysis'],
            'tools' => ['repository_read', 'pull_request_read', 'web_search'],
        ],
        'kimi_flagship' => [
            'provider' => 'kimi',
            'model' => env('KIMI_FLAGSHIP_MODEL'),
            'capabilities' => ['reasoning', 'coding', 'large_context', 'structured_output', 'tool_calling'],
            'tools' => ['repository_read', 'pull_request_read', 'web_search'],
        ],
        'kimi_code' => [
            'provider' => 'kimi',
            'model' => env('KIMI_CODE_MODEL'),
            'capabilities' => ['coding', 'large_context', 'structured_output', 'tool_calling'],
            'tools' => ['repository_read', 'pull_request_read'],
        ],
        'xai_growth' => [
            'provider' => 'xai',
            'model' => env('XAI_GROWTH_MODEL'),
            'capabilities' => ['reasoning', 'structured_output', 'tool_calling'],
            'tools' => ['web_search', 'social_search'],
        ],
        'security_specialist' => [
            'provider' => env('SECURITY_SPECIALIST_PROVIDER'),
            'model' => env('SECURITY_SPECIALIST_MODEL'),
            'capabilities' => ['reasoning', 'structured_output', 'tool_calling', 'security_analysis'],
            'tools' => ['repository_read', 'pull_request_read'],
        ],
        'reasoning_economy' => [
            'provider' => env('REASONING_ECONOMY_PROVIDER'),
            'model' => env('REASONING_ECONOMY_MODEL'),
            'capabilities' => ['reasoning', 'structured_output', 'tool_calling'],
            'tools' => ['repository_read', 'pull_request_read', 'web_search', 'browser'],
        ],
        'triage_economy' => [
            'provider' => env('TRIAGE_PROVIDER'),
            'model' => env('TRIAGE_MODEL'),
            'capabilities' => ['structured_output'],
            'tools' => [],
        ],
        'writing_general' => [
            'provider' => env('WRITING_PROVIDER'),
            'model' => env('WRITING_MODEL'),
            'capabilities' => ['reasoning', 'structured_output'],
            'tools' => ['web_search'],
        ],
    ],

    'roles' => [
        'chief_executive' => [
            'primary' => 'anthropic_frontier',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'structured_output', 'tool_calling'],
            'required_tools' => ['repository_read', 'web_search'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'chief_operating_officer' => [
            'primary' => 'openai_frontier',
            'fallback' => 'reasoning_economy',
            'required_capabilities' => ['reasoning', 'structured_output', 'tool_calling'],
            'required_tools' => ['repository_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'balanced',
        ],
        'chief_technology_officer' => [
            'primary' => 'openai_frontier',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning', 'coding', 'large_context'],
            'required_tools' => ['repository_read', 'pull_request_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'chief_product_officer' => [
            'primary' => 'anthropic_frontier',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['repository_read', 'web_search'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'chief_marketing_growth' => [
            'primary' => 'xai_growth',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'chief_finance_commercial' => [
            'primary' => 'openai_frontier',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],

        'engineering_orchestrator' => [
            'primary' => 'openai_frontier',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning', 'coding', 'tool_calling'],
            'required_tools' => ['repository_read', 'pull_request_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'software_architect' => [
            'primary' => 'anthropic_frontier',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'coding', 'large_context'],
            'required_tools' => ['repository_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'implementation_complex' => [
            'primary' => 'openai_frontier',
            'fallback' => 'kimi_flagship',
            'required_capabilities' => ['reasoning', 'coding', 'tool_calling'],
            'required_tools' => ['repository_read'],
            'permissions' => ['execute_write' => true, 'review' => false, 'approve' => false],
            'preference' => 'quality',
        ],
        'implementation_standard' => [
            'primary' => 'kimi_code',
            'fallback' => 'kimi_flagship',
            'required_capabilities' => ['coding'],
            'required_tools' => ['repository_read'],
            'permissions' => ['execute_write' => true, 'review' => false, 'approve' => false],
            'preference' => 'balanced',
        ],
        'repo_investigator' => [
            'primary' => 'kimi_flagship',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['large_context'],
            'required_tools' => ['repository_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'independent_pr_reviewer' => [
            'primary' => 'anthropic_frontier',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'coding'],
            'required_tools' => ['pull_request_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => true],
            'preference' => 'quality',
        ],
        'security_reviewer' => [
            'primary' => 'security_specialist',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning', 'security_analysis'],
            'required_tools' => ['repository_read', 'pull_request_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'qa_verification' => [
            'primary' => 'reasoning_economy',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning', 'tool_calling'],
            'required_tools' => ['repository_read'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'cost',
        ],
        'triage_summary' => [
            'primary' => 'triage_economy',
            'fallback' => 'reasoning_economy',
            'required_capabilities' => ['structured_output'],
            'required_tools' => [],
            'permissions' => ['execute_write' => false, 'review' => false, 'approve' => false],
            'preference' => 'cost',
        ],
        'content_strategist' => [
            'primary' => 'xai_growth',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'content_researcher' => [
            'primary' => 'xai_growth',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => false, 'review' => false, 'approve' => false],
            'preference' => 'balanced',
        ],
        'content_builder' => [
            'primary' => 'xai_growth',
            'fallback' => 'writing_general',
            'required_capabilities' => ['structured_output'],
            'required_tools' => [],
            'permissions' => ['execute_write' => true, 'review' => false, 'approve' => false],
            'preference' => 'balanced',
        ],
        'market_intelligence' => [
            'primary' => 'xai_growth',
            'fallback' => 'openai_frontier',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => false, 'review' => false, 'approve' => false],
            'preference' => 'quality',
        ],
        'commercial_strategist' => [
            'primary' => 'xai_growth',
            'fallback' => 'anthropic_frontier',
            'required_capabilities' => ['reasoning'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => false, 'review' => true, 'approve' => false],
            'preference' => 'quality',
        ],
        'product_marketing' => [
            'primary' => 'xai_growth',
            'fallback' => 'writing_general',
            'required_capabilities' => ['reasoning', 'structured_output'],
            'required_tools' => ['web_search'],
            'permissions' => ['execute_write' => true, 'review' => false, 'approve' => false],
            'preference' => 'balanced',
        ],
    ],
];
